### ISSUE TITLE
black background

### ISSUE THREAD

**Issue by stephenrparsons** [viscenter/layered-viewer#13]

**Comment by johnwalker** [comment]
btw your commits are showing up as root for some reason

**Comment by stephenrparsons** [comment]
Made a few changes on the live code on infoforest, which required me to run as root. I'll stop doing that (change code locally and pull on infoforest).

**Comment by johnwalker** [comment]
ok. i'll rewrite those into your name later

**Comment by stephenrparsons** [comment]
Done by changing background-color of secondary canvas element. Closing #13.
