### ISSUE TITLE
resizing messes up canvas

### ISSUE THREAD

**Issue by johnwalker** [viscenter/layered-viewer#14]
for example, try opening firefox dev tools with the client open and closing the dev tools. the secondary canvas will be larger than the primary canvas

**Comment by johnwalker** [comment]
I'm not really sure what the best approach here is. The same css is being applied to both canvas elements, aside from z-index. Changing zoom resyncs the sizes. So it's obviously not a css issue, but changing both canvas elements to fixed pixel width would fix the issue. But we would run into problems later with fullscreen, and so it's better to just address the problem now. I am 99% it is an openseadragon detail that I haven't picked up on yet.

**Comment by csparker247** [comment]
Debug mode may help you: http://openseadragon.github.io/examples/developer-debug-mode/

My bet is that the OSD zoom level is being calculated differently for each canvas when the window size scales. The canvases only sync their zoom level when OSD's zoom function is used, but the canvases have to reevaluate their zoom level if they change size, which is a different thing entirely. Why they would calculate too different zoom levels, I don't know, but it certainly seems to explain how they could potentially get out of sync.

**Comment by johnwalker** [comment]
yeah, in retrospect it's a safe bet to say that resizing is messing up the viewport's zoom. i don't think the fix is straightforward though. for now we should patch it over by listening to resize and syncing the secondary clients settings to the primary's then also.

later we should kill all of these events and patch the second client so that it doesnt calculate these things and just uses the primary clients members.
