### ISSUE TITLE
When switching from circle to square with 'c' make it instant

### ISSUE THREAD

**Issue by stephenrparsons** [viscenter/layered-viewer#19]
Right now it does not change the shape until the mouse is moved. The switch does call drawopacity() so I am not sure why the update is not instant.

**Comment by johnwalker** [comment]
that is because drawopacity doesnt really draw anything. it returns a function that draws something. rename drawopacity to makedrawfn or something less confusing, and in this case use it like:

```
mydrawfn = makedrawfn(true, true);
addEventListener("foobar", mydrawfn);
```

**Comment by stephenrparsons** [comment]
What would be the best approach to have a draw() function that could be called anywhere and would do what we expect? That would be quite handy.

**Comment by johnwalker** [comment]
can you be more specific about what you expect?

**Comment by johnwalker** [comment]
the point of manufacturing the function like this is that the drawfn will vary (slightly) depending on whether you want to redraw the primary canvas and whether it should (can) update the last known position of the mouse.

**Comment by johnwalker** [comment]
Check if my last commit fixed it.

**Comment by stephenrparsons** [comment]
Yeah, that makes more sense to me now. Silly me hadn't registered that it
was returning a function, which is clear, I just wasn't paying attention.
Thanks for comments too, cleared it up significantly for me.

**Comment by johnwalker** [comment]
ok cool. if you think there is a descriptive function name in particular that you want, i'm totally open to not doing things like makedrawfn(true,true)({}) or whatever. it's just that the names i could think of were things like

```
forceredrawandupdatemouseposanddrawthingy(e)
dontforceredrawandupdatemouseposanddrawthingy(e)
.
.
.
```
