### ISSUE TITLE
On shift+scroll to resize clipping region, OSD also zooms out

### ISSUE THREAD

**Issue by stephenrparsons** [viscenter/layered-viewer#20]
This happens regardless of the direction the clipping region is being grown.

**Comment by johnwalker** [comment]
do we have a list of keys in mind and what they are supposed to do?

**Comment by johnwalker** [comment]
patch the primary client's onCanvasScroll function to do whatever it is you want. just do a search for the function name. same strategy for anything else

http://openseadragon.github.io/docs/openseadragon.js.html
