### ISSUE TITLE
minimap nav tool

### ISSUE THREAD

**Issue by stephenrparsons** [viscenter/layered-viewer#27]
@csparker247 do you want to have the minimap navigation tool in the corner as shown here?

Does anyone else have an opinion on this?

![screenshot from 2015-04-20 20 58 38](https://cloud.githubusercontent.com/assets/4584652/7243799/5abecf76-e7a0-11e4-8eca-290622d4dd1d.png)

**Comment by csparker247** [comment]
I think it'd be good to have. 

EDIT: I'm not sure what control we have over the minimap, but its default size on large window resolutions is a little unwieldy. It also seems to get set to a static size on page load, which seems like an odd choice on OSD's part.
