### ISSUE TITLE
make page and layer navigation interact with SLY nav bar

### ISSUE THREAD

**Issue by stephenrparsons** [viscenter/layered-viewer#29]

**Comment by johnwalker** [comment]
i'd say this and #26 and #7  are the main issues worth spending time on before the presentation tomorrow (today?)

**Comment by johnwalker** [comment]
i'm ok with faking some functionality for the sake of demoing.

**Comment by stephenrparsons** [comment]
I agree, I will work on this tonight/in the morning.

**Comment by stephenrparsons** [comment]
Closing #29
