### ISSUE TITLE
weird bouncy scrolling in OSX Chrome

### ISSUE THREAD

**Issue by stephenrparsons** [viscenter/layered-viewer#31]
try this: http://stackoverflow.com/questions/4770025/how-to-disable-scrolling-temporarily

**Comment by johnwalker** [comment]
so is this specific to osx chrome or does this happen on ubuntu also?

**Comment by stephenrparsons** [comment]
I do not have this behavior on ubuntu chrome.

**Comment by csparker247** [comment]
It's OSX specific.

http://stackoverflow.com/questions/12046315/prevent-overscrolling-of-web-page

**Comment by johnwalker** [comment]
this also might be fixed.
