### ISSUE TITLE
retina displays are stupid

### ISSUE THREAD

**Issue by johnwalker** [viscenter/layered-viewer#35]
https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/HTML-canvas-guide/SettingUptheCanvas/SettingUptheCanvas.html

**Comment by johnwalker** [comment]
the good news is that it's a 10 minute fix. if a scale factor is defined, multiply by that. otherwise define the scale factor as 1

**Comment by stephenrparsons** [comment]
Great, thanks for investigating. In the next couple of days I will be
looking at some other issues and can knock this out if it still remains.

**Comment by johnwalker** [comment]
@csparker247 would you check infoforest.vis.uky.edu and see if the issue is fixed? try on safari and chrome

**Comment by johnwalker** [comment]
well retina displays might not be fixed but maybe the client is fixed on retina displays

**Comment by csparker247** [comment]
Mouse now accurately tracks position in Chrome and Safari on both retina and non-retina.

However, the mouse now has a trail in in Safari (Retina and non-retina both): https://drive.google.com/file/d/0BxjtEz6no21sZVZqR283LWZIc1E/view?usp=sharing

**Comment by johnwalker** [comment]
LOL we implemented painting
