### ISSUE TITLE
parse JSON image set files and display accordingly

### ISSUE THREAD

**Issue by stephenrparsons** [viscenter/layered-viewer#5]

**Comment by stephenrparsons** [comment]
also verify valid json schema when loading json into viewer http://json-schema.org/

**Comment by johnwalker** [comment]
are you working on this

**Comment by stephenrparsons** [comment]
will complete today

**Comment by stephenrparsons** [comment]
Now reads dzi files from default json file (currently using test file). See separate issue #16 for JSON schema validation. Closing #5.

**Comment by johnwalker** [comment]
awesome, thanks
