### ISSUE TITLE
Backend dzi serving

### ISSUE THREAD

**Issue by stephenrparsons** [viscenter/layered-viewer#8]
Not much more is needed than a simple HTTP server. As we know the whole thing can essentially be done with `python -m SimpleHTTPServer 8000` but we probably want something more robust.

**Comment by johnwalker** [comment]
what is more robust than an httpserver

**Comment by thomasloy** [comment]
John has a good point. In what sense do you mean robust in this case Stephen?

**Comment by johnwalker** [comment]
took a second to get the link right, how is this

http://infoforest.vis.uky.edu

**Comment by johnwalker** [comment]
@thomasloy i think he was just saying that we should use something more viable for long term than python's http server

**Comment by thomasloy** [comment]
Cool. Do we have any leading candidates for that?

**Comment by stephenrparsons** [comment]
Agreed with John that we can use the existing Apache server on
infoforest.vis.uky.edu, we will just need to change its directory to our
layered-viewer directory.

**Comment by johnwalker** [comment]
ok, test thing is displayed on infoforest.
