### ISSUE TITLE
group dzi's into json

### ISSUE THREAD

**Issue by johnwalker** [viscenter/layered-viewer#9]
earlier we talked about using json as a format for specifying collections of dzis. we need to do that before we can address #7  . Unfortunately, this part has to be done by hand since the documents have a very complex naming scheme.

**Comment by stephenrparsons** [comment]
Script is in scripts directory. The chad3json.py script should be run from the images directory. chad.json is stored in data directory. Closing #9

**Comment by johnwalker** [comment]
awesome
